name: my-workflow
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo ln -s /usr/bin/krb5-config.mit /usr/bin/krb5-config
          sudo ln -s /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 /usr/lib/libgssapi_krb5.so
          sudo apt-get install python-pip libkrb5-dev
          sudo pip install gssapi
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -vv
